npmScopes:
  coderatparadise:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.1.1.cjs
