npmScopes:
  coderatparadise:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpFallbackMode: all

yarnPath: .yarn/releases/yarn-3.1.1.cjs
